substitutions:
  host_name: bt-proxy-01
  device_name: Svetlana's Room BT Control

esphome:
  name: ${host_name}
  friendly_name: ${device_name}
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

web_server:
  port: 80
  include_internal: true

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  ap:
    ssid: ${device_name}
    password: !secret ap_password

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true

ble_adv_proxy:
  use_max_tx_power: true # see below, remove in case of build issues

external_components:
  source: github://NicoIIT/esphome-ble_adv_proxy

button:
  - platform: safe_mode
    id: button_safe_mode
    name: Safe Mode Boot

  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset