substitutions:
  host_name: esp-cam-01
  device_name: ESP Cam 01

esphome:
  name: ${host_name}
  friendly_name: ${device_name}
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

web_server:
  port: 80
  include_internal: true

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  ap:
    ssid: ${device_name}
    password: !secret ap_password

esp32_camera:
  id: access_cam
  name: Access Control Camera
  external_clock:
    pin: GPIO0
    frequency: 10MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 800x600
  jpeg_quality: 10  # max. 63
  max_framerate: 1.0fps
  idle_framerate: 0.2fps
#  vertical_flip: true
  horizontal_mirror: false
  brightness: 2 # -2 to 2
  contrast: 1 # -2 to 2
  special_effect: none
  # exposure settings
  aec_mode: auto
  aec2: false
  ae_level: 0
  aec_value: 300
  # gain settings
  agc_mode: auto
  agc_gain_ceiling: 2x
  agc_value: 0
  # white balance setting
  wb_mode: auto

output:
# white LED
  - platform: ledc
    channel: 2
    pin: GPIO4
    id: work_light
# red status light
  - platform: gpio
    pin:
      number: GPIO33
      inverted: True
    id: status_light

light:
  - platform: monochromatic
    output: work_light
    name: Camera Work Light
  - platform: binary
    output: status_light
    name: Camera Status Light

switch:
  - platform: restart
    name: Camera Restart

binary_sensor:
  - platform: status
    name: Camera On

sensor:
  - platform: wifi_signal
    name: Camera WiFi Signal